version: '3.8'

services:
  device-server:
    image: smart-home-dashboard-image:latest
    container_name: device-server
    command: ["java", "-cp", "app.jar", "org.example.smartHome.network.DeviceServer"]
    ports:
      - "12345:12345"
    networks:
      - iot-net

  smart-home-dashboard:
    image: smart-home-dashboard-image:latest
    container_name: smart-home-dashboard
    command: ["java", "-cp", "app.jar", "org.example.smartHome.Main"]
    environment:
      - DEVICE_SERVER_HOST=device-server
    stdin_open: true
    tty: true
    depends_on:
      - device-server
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
